name: freerave
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_app_check: ^0.3.0+4
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.0.1
  flutter_multi_formatter: ^2.13.0
  geolocator: ^12.0.0
  intl_phone_number_input: ^0.7.4
  shared_preferences: ^2.3.2
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  speech_to_text: ^6.6.0
  avatar_glow: ^3.0.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  equatable: ^2.0.5
  flutter_barcode_scanner: ^2.0.0
  otp: ^3.1.4
  barcode_widget: ^2.0.4
  qr_flutter: ^4.1.0
  flutter_secure_storage: ^9.2.2
  flutter_password_strength: ^0.1.6
  crypto: ^3.0.5
  stream_chat_flutter: ^8.0.0
  photo_manager: ^3.3.0
  flutter_localization: ^0.2.1
  flutter_portal: ^1.1.4
  rxdart: ^0.27.7
  logger: ^2.4.0
  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
